language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
- docker
env:
  global:
  - PINS="sidekick:."
  - DISTRO="ubuntu-16.04"
  matrix:
  #- PACKAGE="sidekick" OCAML_VERSION="4.02.3"
  - PACKAGE="sidekick" OCAML_VERSION="4.03"
  - PACKAGE="sidekick" OCAML_VERSION="4.04"
  - PACKAGE="sidekick" OCAML_VERSION="4.05"
  - PACKAGE="sidekick" OCAML_VERSION="4.06"
